### ISSUE TITLE
Preprocess and matlab code？

### ISSUE THREAD

**Issue by MayYoY** [LuPaoPao/NEST-rPPG#1]
Will hr preprocess and matlab code be released?

**Comment by LuPaoPao** [comment]
preprocess :https://github.com/LuPaoPao/NEST-rPPG/tree/main/STMap/VIPL

**Comment by LuPaoPao** [comment]
Matlab for eval：https://github.com/LuPaoPao/NEST-rPPG/tree/main/Eval_from_BVP

**Comment by LuPaoPao** [comment]
> Will hr preprocess and matlab code be released?
preprocess :https://github.com/LuPaoPao/NEST-rPPG/tree/main/STMap/VIPL
Matlab for eval：https://github.com/LuPaoPao/NEST-rPPG/tree/main/Eval_from_BVP

if you want well processed STMap and ground truth： please drop me a email
