### ISSUE TITLE
Apply for Well-Processed STMaps and Ground Truth Labels from Five Datasets

### ISSUE THREAD

**Issue by cancan520** [LuPaoPao/NEST-rPPG#2]
Dear Hao Lu,

I am a graduate student from the School of Data Science at City University of Macau, and I recently had the pleasure of reading your paper on NEST. I found the method you presented to be very impressive, and I am interested in conducting further research on this topic.

During my visit to your GitHub, I noticed that you mentioned providing all well-processed STMaps and ground truth labels from five datasets. I am wondering if it would be possible to obtain these materials from you to aid in my testing and analysis.

I have previously sent you an email requesting an STMap, but I have been unable to send it. If you have seen my message on GitHub, please feel free to contact my email address: d22091100457@cityu.mo

Thank you very much for your time and consideration.

Best regards,
CAN LIN

**Comment by LuPaoPao** [comment]
Thanks for you attention, I will give a email for you~

**Comment by LuPaoPao** [comment]
Thanks for you attention, I will give a email for you~
