### ISSUE TITLE
Apply for the well-processed data

### ISSUE THREAD

**Issue by MayYoY** [LuPaoPao/NEST-rPPG#3]
Dear Hao Lu,

I am a master candidate at University of Science and Technology of China. Presently, I am researching some related issues and trying to reproduce the NEST-rPPG paper.  As a result, I wonder if you can send me well-processed STMap and groud truth labels, which would be of great help for me.

I have previously sent you an email requesting for the data but still haven’t received a reply. If you have seen this issue on GitHub, please feel free to contact my email address: 201930361470@mail.scut.edu.cn

I would appreciate it if you could reply as soon as possible, thank you very much!

Best regards,
Liang qian

**Comment by LuPaoPao** [comment]
I have sent U a email.

**Comment by LuPaoPao** [comment]
> Dear Hao Lu,
> 
> I am a master candidate at University of Science and Technology of China. Presently, I am researching some related issues and trying to reproduce the NEST-rPPG paper. As a result, I wonder if you can send me well-processed STMap and groud truth labels, which would be of great help for me.
> 
> I have previously sent you an email requesting for the data but still haven’t received a reply. If you have seen this issue on GitHub, please feel free to contact my email address: [201930361470@mail.scut.edu.cn](mailto:201930361470@mail.scut.edu.cn)
> 
> I would appreciate it if you could reply as soon as possible, thank you very much!
> 
> Best regards, Liang qian
I have sent U a email.
