### ISSUE TITLE
Apply for the V4V well-processed data about V4V

### ISSUE THREAD

**Issue by sunburst89757** [LuPaoPao/NEST-rPPG#4]
Dear Hao Lu,

I am a master student at Wuhan University of Technology of China. Presently, I am researching some related issues about V4V database. As a result, I wonder if you can send me the V4V STMap 、Generate the preprocessing code of V4V STAMP similar to your open source BUAA code 、groud truth labels and Generate the ground truth code of V4V , which would be of great help for me.

I have previously sent you an email requesting for the data but still haven’t received a reply. If you have seen this issue on GitHub, please feel free to contact my email address: 247401754@whut.edu.cn

I would appreciate it if you could reply as soon as possible, thank you very much!

Best regards

**Comment by LuPaoPao** [comment]
> Dear Hao Lu,
> 
> I am a master student at Wuhan University of Technology of China. Presently, I am researching some related issues about V4V database. As a result, I wonder if you can send me the V4V STMap 、Generate the preprocessing code of V4V STAMP similar to your open source BUAA code 、groud truth labels and Generate the ground truth code of V4V , which would be of great help for me.
> 
> I have previously sent you an email requesting for the data but still haven’t received a reply. If you have seen this issue on GitHub, please feel free to contact my email address: [247401754@whut.edu.cn](mailto:247401754@whut.edu.cn)
> 
> I would appreciate it if you could reply as soon as possible, thank you very much!
> 
> Best regards

Here:

IP：111.230.64.2
ID：NEST
Code：dvlab2023+++
Data Path: /home/NEST/STMap.zip


I don't know why I can't receive your email.
I am very sorry for that.

**Comment by sunburst89757** [comment]
sorry, I can't open the ip you mentioned, is there any other operation required? thank you.
![image](https://github.com/LuPaoPao/NEST-rPPG/assets/82217593/2e28a25f-0cc7-476b-9772-1a0f6aeaca8d)

**Comment by LuPaoPao** [comment]
> sorry, I can't open the ip you mentioned, is there any other operation required? thank you. ![image](https://user-images.githubusercontent.com/82217593/241718867-2e28a25f-0cc7-476b-9772-1a0f6aeaca8d.png)

please use ssh.

**Comment by sunburst89757** [comment]
thanks to your guidance, I successfully download the well processed STMap and ground truth. thank you very much ！！！ but I still have one  small request that could you please send me the Generate the preprocessing code of V4V STAMP similar to your open source BUAA code and Generate the ground truth code of V4V ? if it is ok,  I would be very grateful.

**Comment by LuPaoPao** [comment]
> thanks to your guidance, I successfully download the well processed STMap and ground truth. thank you very much ！！！ but I still have one small request that could you please send me the Generate the preprocessing code of V4V STAMP similar to your open source BUAA code and Generate the ground truth code of V4V ? if it is ok, I would be very grateful.

Ok, but I'm going to give you a very confusing code. 
I hope you can run successfully.
