### ISSUE TITLE
关于STMap的生成问题

### ISSUE THREAD

**Issue by TomBlackH** [LuPaoPao/NEST-rPPG#6]
你好，请问为什么我的视频帧数是25FPS的，生成出来的STMap有明显割裂感呢？

![image](https://github.com/EnVision-Research/NEST-rPPG/assets/53959312/ebfa5956-a6f5-4215-961d-ac1e1e99d1c9)

我在这里已经改了插帧的参数信息，但是生成出来的还是有明显割裂感，请问这是什么问题呢？

![image](https://github.com/EnVision-Research/NEST-rPPG/assets/53959312/096fadc1-1973-4993-b1e6-dab7e6990bdf)

**Comment by TomBlackH** [comment]
数据源是UBFC-rPPG的 11-gt

**Comment by LuPaoPao** [comment]
Thanks for your attention, my original UBFC frame rate here is around 30. Have you processed a video and then saved it again?

 **11-gt**
ffmpeg -i vid.avi 2>&1 | grep "fps"
    Stream #0:0: Video: rawvideo, bgr24, 640x480, 211483 kb/s, 28.67 fps, 28.67 tbr, 28.67 tbn, 28.67 tbc

> 数据源是UBFC-rPPG的 11-gt
