### ISSUE TITLE
the folder number and ID of VIPL-HR dataset

### ISSUE THREAD

**Issue by Snopylz** [LuPaoPao/NEST-rPPG#7]
Thank you for sharing your code. I am very interested in your work and would like to replicate the process of generating STmaps on VIPL-HR. Additionally, I have read the paper "rPPG-MAE: Self-supervised Pretraining with Masked Autoencoders for Remote Physiological Measurements" and would like to know which visible light videos from the VIPL-HR dataset were used, as the number of STmaps downloaded does not match the 2378 videos mentioned in the dataset description.

Thanks for sharing

**Comment by MayYoY** [comment]
I have the same question.

**Comment by LuPaoPao** [comment]
There is indeed such a problem. Because I have cleaned some missing marked data and abnormal samples from VIPL, the number of samples is different. Sorry about that.
