### ISSUE TITLE
how to generate the label of VIPL

### ISSUE THREAD

**Issue by Bagfish** [LuPaoPao/NEST-rPPG#8]
i want to use to code in "STMap/VIPL" folder to generate the stmaps and the label of the VIPL dataset by myself, but i followed the 4 steps in readme.txt, i just found the stmaps were generated. Could you give me some guides about how to generate the label for VIPL. Thank you very much!

**Comment by LuPaoPao** [comment]
> i want to use to code in "STMap/VIPL" folder to generate the stmaps and the label of the VIPL dataset by myself, but i followed the 4 steps in readme.txt, i just found the stmaps were generated. Could you give me some guides about how to generate the label for VIPL. Thank you very much!

I am very sorry about this, but the code generated by VIPL's annotations is very old and can no longer be found. I'm terribly sorry.

**Comment by selena531** [comment]
> i want to use to code in "STMap/VIPL" folder to generate the stmaps and the label of the VIPL dataset by myself, but i followed the 4 steps in readme.txt, i just found the stmaps were generated. Could you give me some guides about how to generate the label for VIPL. Thank you very much!

Hava you solve the question? could you please share with me?
